# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TextBrowser = QtWidgets.QListWidget(self.centralwidget)
        self.TextBrowser.setObjectName("TextBrowser")
        item = QtWidgets.QListWidgetItem()
        self.TextBrowser.addItem(item)
        self.gridLayout.addWidget(self.TextBrowser, 0, 0, 4, 1)
        self.ButtonBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.gridLayout.addWidget(self.ButtonBrowse, 0, 1, 1, 2)
        self.TextOutput = QtWidgets.QListWidget(self.centralwidget)
        self.TextOutput.setObjectName("TextOutput")
        self.gridLayout.addWidget(self.TextOutput, 0, 3, 4, 1)
        self.ButtonImportKey = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonImportKey.setObjectName("ButtonImportKey")
        self.gridLayout.addWidget(self.ButtonImportKey, 1, 1, 1, 2)
        self.ButtonEncrypte = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonEncrypte.setObjectName("ButtonEncrypte")
        self.gridLayout.addWidget(self.ButtonEncrypte, 2, 1, 1, 2)
        self.ButtonDecrypte = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDecrypte.setObjectName("ButtonDecrypte")
        self.gridLayout.addWidget(self.ButtonDecrypte, 3, 1, 1, 2)
        self.TextPublicKey = QtWidgets.QListWidget(self.centralwidget)
        self.TextPublicKey.setObjectName("TextPublicKey")
        item = QtWidgets.QListWidgetItem()
        self.TextPublicKey.addItem(item)
        self.gridLayout.addWidget(self.TextPublicKey, 4, 0, 1, 2)
        self.TextPrivateKey = QtWidgets.QListWidget(self.centralwidget)
        self.TextPrivateKey.setObjectName("TextPrivateKey")
        item = QtWidgets.QListWidgetItem()
        self.TextPrivateKey.addItem(item)
        self.gridLayout.addWidget(self.TextPrivateKey, 4, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab #4 Savchuk Bohdan"))
        __sortingEnabled = self.TextBrowser.isSortingEnabled()
        self.TextBrowser.setSortingEnabled(False)
        item = self.TextBrowser.item(0)
        item.setText(_translate("MainWindow", "Push \"Browse\" button to browse files"))
        self.TextBrowser.setSortingEnabled(__sortingEnabled)
        self.ButtonBrowse.setText(_translate("MainWindow", "Browse"))
        self.ButtonImportKey.setText(_translate("MainWindow", "Import keys"))
        self.ButtonEncrypte.setText(_translate("MainWindow", "Encrypte"))
        self.ButtonDecrypte.setText(_translate("MainWindow", "Decrypte"))
        __sortingEnabled = self.TextPublicKey.isSortingEnabled()
        self.TextPublicKey.setSortingEnabled(False)
        item = self.TextPublicKey.item(0)
        item.setText(_translate("MainWindow", "Waiting for a public key"))
        self.TextPublicKey.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.TextPrivateKey.isSortingEnabled()
        self.TextPrivateKey.setSortingEnabled(False)
        item = self.TextPrivateKey.item(0)
        item.setText(_translate("MainWindow", "Waiting for a private key"))
        self.TextPrivateKey.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "Public key"))
        self.label_2.setText(_translate("MainWindow", "Private key"))
